param(
    [string]$SeedSql = "database/InsertData.sql",
    [string]$GoodsDir = "backend/storage/goods-img",
    [string]$OutputSql = "database/migrations/V20260308_05_fill_goods_images_from_dummyjson.sql",
    [int]$DownloadCount = 100
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

if (!(Test-Path $SeedSql)) {
    throw "Seed SQL file not found: $SeedSql"
}

if (!(Test-Path $GoodsDir)) {
    New-Item -ItemType Directory -Force -Path $GoodsDir | Out-Null
}

if ($DownloadCount -lt 1) {
    throw "DownloadCount must be >= 1"
}

$limit = [Math]::Min([Math]::Max($DownloadCount, 1), 194)
$url = "https://dummyjson.com/products?limit=$limit"
$resp = Invoke-RestMethod -Uri $url -Method Get
$products = @($resp.products)
if ($products.Count -eq 0) {
    throw "No products returned from dummyjson API"
}

$thumbUrls = @(
    $products |
        ForEach-Object { $_.thumbnail } |
        Where-Object { $_ -and $_.Trim().Length -gt 0 } |
        Select-Object -Unique
)

if ($thumbUrls.Count -eq 0) {
    throw "No thumbnail URLs in dummyjson response"
}

$localPaths = @()
$index = 1
foreach ($thumb in $thumbUrls) {
    $uri = [Uri]$thumb
    $ext = [IO.Path]::GetExtension($uri.AbsolutePath)
    if ([string]::IsNullOrWhiteSpace($ext)) {
        $ext = ".jpg"
    }

    $fileName = ("dummyjson-{0:D3}{1}" -f $index, $ext.ToLowerInvariant())
    $target = Join-Path $GoodsDir $fileName
    if (!(Test-Path $target)) {
        Invoke-WebRequest -Uri $thumb -OutFile $target -UseBasicParsing
    }
    $localPaths += "/goods-img/$fileName"
    $index += 1
}

$content = Get-Content $SeedSql -Raw
$block = [regex]::Match($content, '(?is)INSERT INTO\s+`?Beyeah_mall_goods_info`?.*?;').Value
if ([string]::IsNullOrWhiteSpace($block)) {
    throw "Cannot find goods INSERT block in $SeedSql"
}

$goodsIds = @(
    [regex]::Matches($block, "\((\d+),") |
        ForEach-Object { [int]$_.Groups[1].Value } |
        Sort-Object -Unique
)

if ($goodsIds.Count -eq 0) {
    throw "No goods IDs parsed from seed SQL"
}

$sqlLines = @()
$sqlLines += "-- Auto generated by scripts/assets/fill-goods-images-from-dummyjson.ps1"
$sqlLines += ("-- Generated at: {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"))
$sqlLines += ("-- Source API: {0}" -f $url)
$sqlLines += ("-- Local files count: {0}" -f $localPaths.Count)
$sqlLines += "START TRANSACTION;"

for ($i = 0; $i -lt $goodsIds.Count; $i++) {
    $goodsId = $goodsIds[$i]
    $imgPath = $localPaths[$i % $localPaths.Count]
    $sqlLines += "UPDATE Beyeah_mall_goods_info SET goods_cover_img='$imgPath', goods_carousel='$imgPath' WHERE goods_id=$goodsId;"
}

$sqlLines += "COMMIT;"

$sqlDir = Split-Path -Path $OutputSql -Parent
if ($sqlDir -and !(Test-Path $sqlDir)) {
    New-Item -ItemType Directory -Force -Path $sqlDir | Out-Null
}
$sqlLines | Set-Content -Path $OutputSql -Encoding UTF8

Write-Output ("Downloaded/Prepared image files: {0}" -f $localPaths.Count)
Write-Output ("Goods rows to update: {0}" -f $goodsIds.Count)
Write-Output ("Output SQL: {0}" -f $OutputSql)
