param(
    [string]$EnvFile = ".env",
    [string]$GoodsDir = "backend/storage/goods-img",
    [string]$OutputSql = "database/migrations/V20260308_06_fill_phone_images_from_dummyjson_smartphones.sql",
    [string]$PhoneCategoryIds = "45,46,47,51",
    [int]$Limit = 100,
    [switch]$Apply
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

if (!(Test-Path $EnvFile)) {
    throw "Env file not found: $EnvFile"
}

if (!(Test-Path $GoodsDir)) {
    New-Item -ItemType Directory -Force -Path $GoodsDir | Out-Null
}

$cfg = @{}
Get-Content $EnvFile | ForEach-Object {
    if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$') {
        $cfg[$matches[1]] = $matches[2]
    }
}

$dbHost = $cfg["DB_HOST"]
$dbPort = $cfg["DB_PORT"]
$dbName = $cfg["DB_NAME"]
$dbUser = $cfg["DB_USER"]
$dbPass = $cfg["DB_PASSWORD"]

if ([string]::IsNullOrWhiteSpace($dbHost) -or
    [string]::IsNullOrWhiteSpace($dbPort) -or
    [string]::IsNullOrWhiteSpace($dbName) -or
    [string]::IsNullOrWhiteSpace($dbUser)) {
    throw "DB config missing in .env"
}

$safeLimit = [Math]::Min([Math]::Max($Limit, 1), 200)
$api = "https://dummyjson.com/products/category/smartphones?limit=$safeLimit"
$resp = Invoke-RestMethod -Uri $api -Method Get
$products = @($resp.products)
if ($products.Count -eq 0) {
    throw "No smartphone products returned by dummyjson"
}

$thumbs = @(
    $products |
        ForEach-Object { $_.thumbnail } |
        Where-Object { $_ -and $_.Trim().Length -gt 0 } |
        Select-Object -Unique
)

if ($thumbs.Count -eq 0) {
    throw "No thumbnails returned by dummyjson smartphones category"
}

$localPaths = @()
$idx = 1
foreach ($thumb in $thumbs) {
    $uri = [Uri]$thumb
    $ext = [IO.Path]::GetExtension($uri.AbsolutePath)
    if ([string]::IsNullOrWhiteSpace($ext)) {
        $ext = ".jpg"
    }
    $fileName = ("dummyjson-phone-{0:D3}{1}" -f $idx, $ext.ToLowerInvariant())
    $target = Join-Path $GoodsDir $fileName
    if (!(Test-Path $target)) {
        Invoke-WebRequest -Uri $thumb -OutFile $target -UseBasicParsing
    }
    $localPaths += "/goods-img/$fileName"
    $idx += 1
}

$categoryFilter = $PhoneCategoryIds.Split(",") | ForEach-Object { $_.Trim() } | Where-Object { $_ -match '^\d+$' }
if ($categoryFilter.Count -eq 0) {
    throw "PhoneCategoryIds has no valid numeric ids"
}
$inClause = ($categoryFilter -join ",")

$env:MYSQL_PWD = $dbPass
$query = "SELECT goods_id FROM Beyeah_mall_goods_info WHERE goods_category_id IN ($inClause) ORDER BY goods_id ASC;"
$rawIds = & mysql --batch --skip-column-names --default-character-set=utf8mb4 -h $dbHost -P $dbPort -u $dbUser $dbName -e $query
if ($LASTEXITCODE -ne 0) {
    throw "Failed to query phone goods ids from DB"
}

$goodsIds = @($rawIds | Where-Object { $_ -match '^\d+$' } | ForEach-Object { [int]$_ })
if ($goodsIds.Count -eq 0) {
    throw "No goods found for category ids: $PhoneCategoryIds"
}

$sqlLines = @()
$sqlLines += "-- Auto generated by scripts/assets/fill-phone-images-from-dummyjson.ps1"
$sqlLines += ("-- Generated at: {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"))
$sqlLines += ("-- Source API: {0}" -f $api)
$sqlLines += ("-- Phone category ids: {0}" -f $PhoneCategoryIds)
$sqlLines += ("-- Local smartphone image files: {0}" -f $localPaths.Count)
$sqlLines += ("-- Target phone goods rows: {0}" -f $goodsIds.Count)
$sqlLines += "START TRANSACTION;"

for ($i = 0; $i -lt $goodsIds.Count; $i++) {
    $goodsId = $goodsIds[$i]
    $img = $localPaths[$i % $localPaths.Count]
    $sqlLines += "UPDATE Beyeah_mall_goods_info SET goods_cover_img='$img', goods_carousel='$img' WHERE goods_id=$goodsId;"
}

$sqlLines += "COMMIT;"

$outDir = Split-Path -Path $OutputSql -Parent
if ($outDir -and !(Test-Path $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}
$sqlLines | Set-Content -Path $OutputSql -Encoding UTF8

Write-Output ("Smartphone files prepared: {0}" -f $localPaths.Count)
Write-Output ("Phone goods rows: {0}" -f $goodsIds.Count)
Write-Output ("SQL generated: {0}" -f $OutputSql)

if ($Apply) {
    & mysql --default-character-set=utf8mb4 -h $dbHost -P $dbPort -u $dbUser $dbName -e ("source " + (Resolve-Path $OutputSql).Path)
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to apply generated SQL"
    }
    Write-Output "SQL applied to database successfully."
}

